### ISSUE TITLE
Issues report

### ISSUE THREAD

**Issue by emgsilva** [martakostova/timer#1]
Hi Marta,

I have been reporting issues in another github issues: https://github.com/martakostova/pomodoro/issues... This is the github you refer to in the Timer website (http://martakostova.github.io/timer/). However I noticed now that in the "Helper dialogue" of "Timer" you define this github as the place to report issues... 

There are many issues being reported in the other github, which are indeed issues on the version of Timer I have just bought from Apple Store.

Please take action on them, since they really affect the overall application experience.

Cheers!

**Comment by martakostova** [comment]
@emgsilva thank you for this report. A lot things are on the way. Expect new version soon :)

Cheers!

**Comment by emgsilva** [comment]
Great to hear that Marta!

I really like this application, keep up with the good work!

Cheers!
