### ISSUE TITLE
Menubar item now wide enough

### ISSUE THREAD

**Issue by zenspider** [martakostova/timer#2]
I am seeing the seconds getting truncated: ![screen shot 2015-01-15 at 15 51 21](https://cloud.githubusercontent.com/assets/9832/5769321/9e26d8e8-9cce-11e4-806d-30822b2f39ff.png) on OSX 10.10.

I'm not running any hacks to make UI any different from the norm and I don't see any relevant system prefs that might be making things bigger.

**Comment by stulentsev** [comment]
Same here. Happens sometimes, not always.

**Comment by martakostova** [comment]
This is fixed in the new version, Thank you for the feedback!
